#!/bin/bash
#    Begin PBS directives
#PBS -A CSC108
#PBS -l walltime=01:00:00
#    End PBS directives and begin shell commands

# this has to be submitted to dtn queue

cd $PROJWORK/csc108/psvirin/jalien-latest-ja/jalien

module load cray-mpich/7.2.5
module load python/3.4.3
module load python_mpi4py/1.3.1

./jalien JobAgent &

qsub -q titan ./get_rank_and_exec_job.pbs

#aprun -n 16 ./get_rank_and_exec_job.py
