#!/bin/bash
#    Begin PBS directives
#PBS -A CSC108
#PBS -N jalien_titan
#PBS -j oe
#PBS -l walltime=01:00:00,nodes=1
#PBS -l gres=atlas1
#    End PBS directives and begin shell commands

cd $MEMBERWORK/csc108

module load cray-mpich/7.2.5
module load python/3.4.3
module load python_mpi4py/1.3.1

#aprun -n 2 ./test.py
#aprun -n 2 ./get_rank.py

#aprun -n 1 ./sleep_test.sh

aprun -n 16 ./get_rank_and_exec_job.py
